### ISSUE TITLE
Bot Can't Join More Servers

### ISSUE THREAD

**Issue by busybox42** [TheAlienDrew/elite-dangerous-news-discord-bot#14]
Looks like there might be some verification steps that need to be done for the bot to join more servers.
![Screenshot 2023-02-06 232606](https://user-images.githubusercontent.com/2141766/217148222-15230066-ac6a-4313-ba3e-e1b303143d31.png)

**Comment by Andrew-J-Larson** [comment]
The bot has been offline forever now, and I've yet to rework it.
